/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CelebrationsRouteImport } from './routes/celebrations'
import { Route as DestinationWeddingsRouteImport } from './routes/destination-weddings'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MarianeRouteImport } from './routes/mariane'
import { Route as MulticulturalWeddingsRouteImport } from './routes/multicultural-weddings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as StartPlanningRouteImport } from './routes/start-planning'
import { Route as TheExperienceRouteImport } from './routes/the-experience'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as CelebrationsWeLoveIndexRouteImport } from './routes/celebrations-we-love.index'
import { Route as CelebrationsWeLoveSlugRouteImport } from './routes/celebrations-we-love.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationsRoute = CelebrationsRouteImport.update({
  id: '/celebrations',
  path: '/celebrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationWeddingsRoute = DestinationWeddingsRouteImport.update({
  id: '/destination-weddings',
  path: '/destination-weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MarianeRoute = MarianeRouteImport.update({
  id: '/mariane',
  path: '/mariane',
  getParentRoute: () => rootRouteImport,
} as any)
const MulticulturalWeddingsRoute = MulticulturalWeddingsRouteImport.update({
  id: '/multicultural-weddings',
  path: '/multicultural-weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const StartPlanningRoute = StartPlanningRouteImport.update({
  id: '/start-planning',
  path: '/start-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const TheExperienceRoute = TheExperienceRouteImport.update({
  id: '/the-experience',
  path: '/the-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationsWeLoveIndexRoute = CelebrationsWeLoveIndexRouteImport.update({
  id: '/celebrations-we-love/',
  path: '/celebrations-we-love/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationsWeLoveSlugRoute = CelebrationsWeLoveSlugRouteImport.update({
  id: '/celebrations-we-love/$slug',
  path: '/celebrations-we-love/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/celebrations': typeof CelebrationsRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/faq': typeof FaqRoute
  '/mariane': typeof MarianeRoute
  '/multicultural-weddings': typeof MulticulturalWeddingsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/start-planning': typeof StartPlanningRoute
  '/the-experience': typeof TheExperienceRoute
  '/weddings': typeof WeddingsRoute
  '/celebrations-we-love/$slug': typeof CelebrationsWeLoveSlugRoute
  '/celebrations-we-love/': typeof CelebrationsWeLoveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/celebrations': typeof CelebrationsRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/faq': typeof FaqRoute
  '/mariane': typeof MarianeRoute
  '/multicultural-weddings': typeof MulticulturalWeddingsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/start-planning': typeof StartPlanningRoute
  '/the-experience': typeof TheExperienceRoute
  '/weddings': typeof WeddingsRoute
  '/celebrations-we-love/$slug': typeof CelebrationsWeLoveSlugRoute
  '/celebrations-we-love': typeof CelebrationsWeLoveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/celebrations': typeof CelebrationsRoute
  '/destination-weddings': typeof DestinationWeddingsRoute
  '/faq': typeof FaqRoute
  '/mariane': typeof MarianeRoute
  '/multicultural-weddings': typeof MulticulturalWeddingsRoute
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/start-planning': typeof StartPlanningRoute
  '/the-experience': typeof TheExperienceRoute
  '/weddings': typeof WeddingsRoute
  '/celebrations-we-love/$slug': typeof CelebrationsWeLoveSlugRoute
  '/celebrations-we-love/': typeof CelebrationsWeLoveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/celebrations'
    | '/destination-weddings'
    | '/faq'
    | '/mariane'
    | '/multicultural-weddings'
    | '/portfolio'
    | '/reviews'
    | '/start-planning'
    | '/the-experience'
    | '/weddings'
    | '/celebrations-we-love/$slug'
    | '/celebrations-we-love/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/celebrations'
    | '/destination-weddings'
    | '/faq'
    | '/mariane'
    | '/multicultural-weddings'
    | '/portfolio'
    | '/reviews'
    | '/start-planning'
    | '/the-experience'
    | '/weddings'
    | '/celebrations-we-love/$slug'
    | '/celebrations-we-love'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/celebrations'
    | '/destination-weddings'
    | '/faq'
    | '/mariane'
    | '/multicultural-weddings'
    | '/portfolio'
    | '/reviews'
    | '/start-planning'
    | '/the-experience'
    | '/weddings'
    | '/celebrations-we-love/$slug'
    | '/celebrations-we-love/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CelebrationsRoute: typeof CelebrationsRoute
  DestinationWeddingsRoute: typeof DestinationWeddingsRoute
  FaqRoute: typeof FaqRoute
  MarianeRoute: typeof MarianeRoute
  MulticulturalWeddingsRoute: typeof MulticulturalWeddingsRoute
  PortfolioRoute: typeof PortfolioRoute
  ReviewsRoute: typeof ReviewsRoute
  StartPlanningRoute: typeof StartPlanningRoute
  TheExperienceRoute: typeof TheExperienceRoute
  WeddingsRoute: typeof WeddingsRoute
  CelebrationsWeLoveSlugRoute: typeof CelebrationsWeLoveSlugRoute
  CelebrationsWeLoveIndexRoute: typeof CelebrationsWeLoveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrations': {
      id: '/celebrations'
      path: '/celebrations'
      fullPath: '/celebrations'
      preLoaderRoute: typeof CelebrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-weddings': {
      id: '/destination-weddings'
      path: '/destination-weddings'
      fullPath: '/destination-weddings'
      preLoaderRoute: typeof DestinationWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mariane': {
      id: '/mariane'
      path: '/mariane'
      fullPath: '/mariane'
      preLoaderRoute: typeof MarianeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multicultural-weddings': {
      id: '/multicultural-weddings'
      path: '/multicultural-weddings'
      fullPath: '/multicultural-weddings'
      preLoaderRoute: typeof MulticulturalWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-planning': {
      id: '/start-planning'
      path: '/start-planning'
      fullPath: '/start-planning'
      preLoaderRoute: typeof StartPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-experience': {
      id: '/the-experience'
      path: '/the-experience'
      fullPath: '/the-experience'
      preLoaderRoute: typeof TheExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrations-we-love/': {
      id: '/celebrations-we-love/'
      path: '/celebrations-we-love'
      fullPath: '/celebrations-we-love/'
      preLoaderRoute: typeof CelebrationsWeLoveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrations-we-love/$slug': {
      id: '/celebrations-we-love/$slug'
      path: '/celebrations-we-love/$slug'
      fullPath: '/celebrations-we-love/$slug'
      preLoaderRoute: typeof CelebrationsWeLoveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CelebrationsRoute: CelebrationsRoute,
  DestinationWeddingsRoute: DestinationWeddingsRoute,
  FaqRoute: FaqRoute,
  MarianeRoute: MarianeRoute,
  MulticulturalWeddingsRoute: MulticulturalWeddingsRoute,
  PortfolioRoute: PortfolioRoute,
  ReviewsRoute: ReviewsRoute,
  StartPlanningRoute: StartPlanningRoute,
  TheExperienceRoute: TheExperienceRoute,
  WeddingsRoute: WeddingsRoute,
  CelebrationsWeLoveSlugRoute: CelebrationsWeLoveSlugRoute,
  CelebrationsWeLoveIndexRoute: CelebrationsWeLoveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
